name: ML App CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Check-out repository
      uses: actions/checkout@v2

    - name: Install poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install

    - name: Install the required Sphinx version
      run: poetry add sphinx@">=5.0,<6.0" --group dev
      
    - name: Run pre-commit checks
      run: poetry run pre-commit run --all-files

    - name: Run pytest
      run: poetry run pytest

    - name: Build documentation
      run: poetry run sphinx-build -b html docs/ docs/_build

    - name: Upload model artifact
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: out.json
